version: '3'

services: 

  backend:
    build: 
      context: ./node
    container_name: backend
    working_dir: /usr/src/app
    environment:
      - MONGO_URI=mongodb+srv://omar:omar@cluster0.6lol0.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    networks: 
      - node-network
    volumes: 
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports: 
      - "3000:3000"
    command: npm start
    depends_on:
       - db

  db:
    image: mongo:latest  
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./data:/data/db   
    ports: 
      - "27017:27017" 
    networks: 
      - node-network

  frontend:
    build: 
      context: ./react
    container_name: frontend
    working_dir: /usr/src/app
    networks: 
      - node-network
    volumes: 
      - ./react:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports: 
      - "5173:5173"
    command: npm run dev -- --host

  

  nginx:
    build: 
      context: ./nginx
    container_name: nginx
    restart: always
    tty: true
    ports: 
      - "8000:80"
    networks: 
      - node-network
    depends_on:
       - backend
       - frontend

networks: 
  node-network:
    driver: bridge
