name: Pull Request Pipeline

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: ./node
        run: |
          npm install

      - name: Install dependencies
        working-directory: ./react
        run: |
          npm install

      - name: Build project
        working-directory: ./node
        run: |
          npm run build

  unit-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Unit Tests 
        working-directory: ./node
        run: |
          npm test

  sonar:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SonarQube Scan 
        run: |
          echo "Run SonarQube scan here"

  integration-tests:
    runs-on: ubuntu-latest
    needs: sonar
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Integration Tests (Backend)
        working-directory: ./node
        run: |
          npm run test
